[tool.poetry]
name = "planetcantile"
version = "0.2.0"
description = "TMS tilesets for Planets"
authors = ["Andrew Annex <ama6fy@virginia.edu>"]
readme = "README.md"
keywords = ["morecantile", "TMS", "TileMatrixSet", "GIS",]
include = ["planetcantile/data/*.json"]
repository = "https://github.com/AndrewAnnex/planetcantile"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: GIS",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License"
]


[tool.poetry.dependencies]
python = "^3.10"
morecantile = "^3.2.1"
click = "^8.1.3"
pyproj = "^3.4.0"
pytest = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
